version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      # Here we dont use something like ./server/Dockerfile.dev coz this is only the name of the file. Location is picked from the context.
      dockerfile: Dockerfile.dev
      context: ./server/.
    volumes:
      - /app/node_modules
      # Here it means that anything if changed in /app, redirect that change to ./server directory.
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # All default configs of postgres
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client/.
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
